services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: "mosquitto"
    restart: unless-stopped
    expose:
      - "1883"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config